name: Filenaming Convention Check

on:
  pull_request:

jobs:
  validate-filename-convention:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate filenames
        run: |
            violations=0
            FOLDER_REGEX='^(agent-management-platform/|agent-platform/|ai-for-process/|ai-for-service/|ai-for-work/)'

            while IFS= read -r file; do
              if [[ "$file" =~ $FOLDER_REGEX ]]; then

                if [[ "$file" =~ [A-Z] || "$file" =~ " " || \
                      "$file" == *"("* || "$file" == *")"* || \
                      "$file" == *"["* || "$file" == *"]"* || \
                      "$file" == *"&"* || "$file" == *"@"* || \
                      "$file" == *"#"* || "$file" == *"%"* || \
                      "$file" == *"+"* || "$file" == *"*"* ]]; then

                  echo "Invalid filename: $file"
                  violations=1
                fi

              fi
            done < <(git diff --name-only origin/${{ github.base_ref }}...HEAD)

            if [ $violations -ne 0 ]; then
              echo "Filename convention violated."
              exit 1
            fi